Add basic CLI
stackhpc/s3-active-storage-rs pull request #28
Opened 2023-03-31 15:48 UTC by sd109

Currently supports host and port args (which can also be set by `S3_ACTIVE_STORAGE_{HOST,PORT}` env vars. Is it worth adding some kind of `--debug` flag for setting log level instead of falling back to `RUST_LOG`?

2023-03-31 15:49 UTC, sd109 commented
Example of current cli output:
```
S3 Active Storage Proxy command line interface

Usage: s3-active-storage [OPTIONS]

Options:
      --host <HOST>  [env: S3_ACTIVE_STORAGE_HOST=] [default: 0.0.0.0]
      --port <PORT>  [env: S3_ACTIVE_STORAGE_PORT=] [default: 8080]
  -h, --help         Print help
```

2023-03-31 15:52 UTC, sd109 commented
Addresses #14

2023-04-03 08:32 UTC, markgoddard requested changes

2023-04-03 08:32 UTC, markgoddard commented on src/main.rs
> +    port: String,
Let's make it a u16 to get some better input validation.

```suggestion
    #[arg(long, default_value = 8080, env = "S3_ACTIVE_STORAGE_PORT")]
    port: u16,
```

2023-04-03 08:32 UTC, markgoddard commented on src/main.rs
> +    port: String,
Or there's this: https://github.com/clap-rs/clap-port-flag

2023-04-03 08:32 UTC, markgoddard commented on src/main.rs
> +    host: String,
How about some short help strings?

2023-04-05 10:29 UTC, sd109 commented
Newer CLI help output with added doc strings:
```
S3 Active Storage Proxy command line interface

Usage: s3-active-storage [OPTIONS]

Options:
      --host <HOST>  The IP address on which the proxy should listen [env: S3_ACTIVE_STORAGE_HOST=] [default: 0.0.0.0]
      --port <PORT>  The port to which the proxy should bind [env: S3_ACTIVE_STORAGE_PORT=] [default: 8080]
  -h, --help         Print help
```

2023-04-05 10:32 UTC, markgoddard approved these changes

2023-04-05 10:51 UTC, merged